# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/e610/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/e610/proprietary/bin/sensord:system/bin/sensord \
    vendor/lge/e610/proprietary/lib/hw/nfc.msm7x27a.so:system/lib/hw/nfc.msm7x27a.so \
    vendor/lge/e610/proprietary/lib/hw/sensors.m4.so:system/lib/hw/sensors.m4.so \
    vendor/lge/e610/proprietary/lib/libchromatix_hi542_default_video.so:system/lib/libchromatix_hi542_default_video.so \
    vendor/lge/e610/proprietary/lib/libchromatix_hi542_preview.so:system/lib/libchromatix_hi542_preview.so \
    vendor/lge/e610/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/lge/e610/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/e610/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/e610/proprietary/bin/rild:system/bin/rild \
    vendor/lge/e610/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/e610/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/lge/e610/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/lge/e610/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/e610/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/e610/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/e610/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/e610/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/e610/proprietary/lib/liblgdrm.so:system/lib/liblgdrm.so \
    vendor/lge/e610/proprietary/lib/liblgeat.so:system/lib/liblgeat.so \
    vendor/lge/e610/proprietary/lib/liblge_security.so:system/lib/liblge_security.so \
    vendor/lge/e610/proprietary/lib/liblgsecclk.so:system/lib/liblgsecclk.so \
    vendor/lge/e610/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/e610/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/e610/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/lge/e610/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/e610/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/lge/e610/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/lge/e610/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/e610/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/e610/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/lge/e610/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/lge/e610/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/e610/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/e610/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/e610/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/lge/e610/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/e610/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/e610/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/e610/proprietary/lib/libwcnftm.so:system/lib/libwcnftm.so \
    vendor/lge/e610/proprietary/lib/libwfcu.so:system/lib/libwfcu.so \
    vendor/lge/e610/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/lge/e610/proprietary/lib/libwmsts.so:system/lib/libwmsts.so
